---
version: '3'
services:
  razor-server:
    build: razor
    ports:
      - "8150:8150"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:9
    environment:
      - 'POSTGRES_PASSWORD=razor'
      - 'POSTGRES_USER=razor'
      - 'POSTGRES_DB=razor'
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'

