# Action taken from https://github.com/filipesilva/ng-github-actions/blob/master/.github/workflows/main.yml

# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Push latest

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    env:
      working-dir: './razorboard'

    steps:
    - uses: actions/checkout@v1
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: wiston999/razorboard/razorboard
        tags: latest
